spring:
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: platformDefaultCircuit
        - name: Retry
          args:
            retries: 2
            backoff:
              firstBackoff: 100ms
              maxBackoff: 1000ms
              factor: 2
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

management:
  metrics:
    web:
      server:
        request:
          matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka/}

resilience4j:
  circuitbreaker:
    instances:
      platformDefaultCircuit:
        slidingWindowSize: 20
        failureRateThreshold: 60
        waitDurationInOpenState: 10s
  ratelimiter:
    instances:
      platformDefaultRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0

gateway:
  telemetry:
    metrics-enabled: true
    traces-enabled: true
    traces-endpoint: http://analytics-collector.arcus-analytics:4318/v1/traces
    metrics-url: http://analytics-collector.arcus-analytics:4318/v1/metrics
  routes:
    path: ${GATEWAY_ROUTES_PATH:/config-repo/routes}
