spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/arcus
    username: arcus
    password: arcus
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level:
    com.arcus.portal: INFO

