spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/arcus
    username: arcus
    password: arcus
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.arcus.portal: INFO

portal:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4173,http://localhost:5173,http://portal-web:4173
  security:
    jwk-set-uri: http://keycloak:8080/realms/arcus/protocol/openid-connect/certs

